#9주차 과제

In [2]:
import numpy as np
import pandas as pd

#pandas 자료구조
#Series
#DataFrame

#Series
#일련의 자료를 담을 수 있는 1차원 배열과 같은 자료구조로, SeRies의 실제 데이터는 numpy의 1차원 array구조로 저장

#Series의 생성
##정수형 인덱스를 갖는 시리즈의 생성

In [3]:

sc = pd.Series([96, 88, 100, 68])
print(sc)

0     96
1     88
2    100
3     68
dtype: int64

##시리즈 객체는 색인과 값을 갖는다.
###시리즈의 색인 확인

In [16]:
#시리즈의 색인 확인
print(sc.index)
#시리즈의 값 확인
print(sc.values)

RangeIndex(start=0, stop=4, step=1)
[ 96  88 100  68]

##문자열을 이용한 색인

In [17]:
obj = pd.Series([96, 88, 100, 69], index=['a', 'b', 'c', 'd'])
print(obj)

#사전 구조를 이용한 시리즈의 생성
dic = {'a' : 96, 'b':88, 'c':100, 'd':68}
obj = pd.Series(dic)
print(obj)

score = pd.Series([96, 88, 100, 68], index=['김은서', '박민철', '정윤주', '홍길동'])
print(score)

a     96
b     88
c    100
d     69
dtype: int64
a     96
b     88
c    100
d     68
dtype: int64
김은서     96
박민철     88
정윤주    100
홍길동     68
dtype: int64

##색인을 이용한 데이터 검색

In [18]:
print(score['정윤주'])
print(score[2])

100
100

##색인을 이용한 데이터 수정

In [19]:
score['박민철'] = 85
print(score)

김은서     96
박민철     85
정윤주    100
홍길동     68
dtype: int64

##특정 조건을 만족하는 값을 가진 데이터 검색
###점수가 80점 이상인 데이터들을 검색하여 출력

In [20]:
print(score[score>=80])

김은서     96
박민철     85
정윤주    100
dtype: int64

##Series 요소의 연산
###pandas 데이터 객체의 모든 요소에 한꺼번에 스칼라 연산이 가능하다.

In [21]:
obj1 = pd.Series([1, 3, 5, 7, 9])
obj2 = obj1 * 2
print(obj2)

0     2
1     6
2    10
3    14
4    18
dtype: int64

###pandas객체에 numpy함수를 적용할 수 있다.

In [22]:
obj1 = pd.Series([1,3,5,7,9])
obj2 = np.sqrt(obj1)
print(obj2)

0    1.000000
1    1.732051
2    2.236068
3    2.645751
4    3.000000
dtype: float64

##코로나19 데이터를 이용한 Series연습
###사전을 이용한 시리즈의 생성
####2021-04-19

In [7]:
covid19 = {'서울' : 35628, '대구' : 9176, '경기' : 31946, '경북' : 3843, '안천' : 5488, '광주' : 2295, '충남': 2886, '부산' : 4670}
covid_19 = pd.Series(covid19)
print(covid_19)

covid_19 = pd.Series([35628, 9176, 31946, 3843, 5488, 2295, 2886, 4670], index=['세울', '대구', '경기', '경북', '안천', '광주', '충남', '부산'])
print(covid_19)

서울    35628
대구     9176
경기    31946
경북     3843
안천     5488
광주     2295
충남     2886
부산     4670
dtype: int64
세울    35628
대구     9176
경기    31946
경북     3843
안천     5488
광주     2295
충남     2886
부산     4670
dtype: int64

###색인 변경

In [10]:
covid_19.index = ['세울', '대구', '경기', '경북', '안천', '광주', '충남', '부산']
covid_19 = covid_19.rename({'세울' : '서울', '안천' : '인천'})
print(covid_19)

covid_19.name = '2021-04-19 COVID19 확진자수'
covid_19.index.name = '지역'
print(covid_19)

서울    35628
대구     9176
경기    31946
경북     3843
인천     5488
광주     2295
충남     2886
부산     4670
Name: 2021-04-19 COVID19 확진자수, dtype: int64
지역
서울    35628
대구     9176
경기    31946
경북     3843
인천     5488
광주     2295
충남     2886
부산     4670
Name: 2021-04-19 COVID19 확진자수, dtype: int64

##DataFrame
###numpy의 2차원 array와 유사

##DataFrame의 생성
###DataFrame: 엑셀의 표와 같은 형식의 자료구조

In [23]:
data = {'지역' : ['서울', '대구', '경기', '경북', '인천', '광주', '충남', '부산'],
    '2020-10-19' : [5702, 7142, 4869, 1573, 999, 502, 505, 571],
    '2021-04-19' : [35628, 9176, 31946, 3843, 5488, 2295, 2886, 4670]
    }
covid_19f = pd.DataFrame(data)
covid_19f.name = '2020년 10월고 ㅏ2021년 4월의 COVID19 확진자수 비교'
print(covid_19f)

   지역  2020-10-19  2021-04-19
0  서울        5702       35628
1  대구        7142        9176
2  경기        4869       31946
3  경북        1573        3843
4  인천         999        5488
5  광주         502        2295
6  충남         505        2886
7  부산         571        4670

###'지역'칼럼을 인덱스로 사용

In [24]:
covid_19f = covid_19f.set_index('지역')
print(covid_19f)

    2020-10-19  2021-04-19
지역
서울        5702       35628
대구        7142        9176
경기        4869       31946
경북        1573        3843
인천         999        5488
광주         502        2295
충남         505        2886
부산         571        4670

###head() 함수 : 처음 5개의 행만 출력

In [25]:
print(covid_19f.head(3))

    2020-10-19  2021-04-19
지역
서울        5702       35628
대구        7142        9176
경기        4869       31946

###사전에 없는 값을 넘기면 결측치로 저장

In [26]:
co210419 = pd.DataFrame(covid_19f, columns=['2021-04-19', '격리해제', '사망', '완치율'])
print(co210419)

    2021-04-19  격리해제  사망  완치율
지역
서울       35628   NaN NaN  NaN
대구        9176   NaN NaN  NaN
경기       31946   NaN NaN  NaN
경북        3843   NaN NaN  NaN
인천        5488   NaN NaN  NaN
광주        2295   NaN NaN  NaN
충남        2886   NaN NaN  NaN
부산        4670   NaN NaN  NaN

###칼럼명 변경

In [27]:
co210419 = co210419.rename({'2021-04-19' : '확진'}, axis=1)
print(co210419)

       확진  격리해제  사망  완치율
지역
서울  35628   NaN NaN  NaN
대구   9176   NaN NaN  NaN
경기  31946   NaN NaN  NaN
경북   3843   NaN NaN  NaN
인천   5488   NaN NaN  NaN
광주   2295   NaN NaN  NaN
충남   2886   NaN NaN  NaN
부산   4670   NaN NaN  NaN

###결측치를 가진 칼럼에 값을 대입

In [28]:
co210419['격리해제'] = 0
co210419['사망'] = 0
co210419['완치율'] = 0
print(co210419)

co210419['격리해제'] = [324643, 4009, 28842, 3515, 5210, 2207, 2652, 4009]
co210419['사망'] = [443, 219, 570, 77, 58, 21, 36, 121]
print(co210419)

       확진  격리해제  사망  완치율
지역
서울  35628     0   0    0
대구   9176     0   0    0
경기  31946     0   0    0
경북   3843     0   0    0
인천   5488     0   0    0
광주   2295     0   0    0
충남   2886     0   0    0
부산   4670     0   0    0
       확진    격리해제   사망  완치율
지역
서울  35628  324643  443    0
대구   9176    4009  219    0
경기  31946   28842  570    0
경북   3843    3515   77    0
인천   5488    5210   58    0
광주   2295    2207   21    0
충남   2886    2652   36    0
부산   4670    4009  121    0

###완치율 계산

In [29]:
co210419['완치율'] = co210419['격리해제']/co210419['확진']
print(co210419)

       확진    격리해제   사망       완치율
지역
서울  35628  324643  443  9.112019
대구   9176    4009  219  0.436901
경기  31946   28842  570  0.902836
경북   3843    3515   77  0.914650
인천   5488    5210   58  0.949344
광주   2295    2207   21  0.961656
충남   2886    2652   36  0.918919
부산   4670    4009  121  0.858458

###DataFrame의 전치 (행과 열을 뒤집음)

In [30]:
print(co210419.T)
co210419 = co210419.astype({'확진' : 'Int32', '격리해제' : 'Int32', '사망' : 'Int32'})
print(co210419.T)

지역               서울           대구  ...           충남           부산
확진     35628.000000  9176.000000  ...  2886.000000  4670.000000
격리해제  324643.000000  4009.000000  ...  2652.000000  4009.000000
사망       443.000000   219.000000  ...    36.000000   121.000000
완치율        9.112019     0.436901  ...     0.918919     0.858458

[4 rows x 8 columns]
지역         서울        대구        경기  ...        광주        충남        부산
확진      35628      9176     31946  ...      2295      2886      4670
격리해제   324643      4009     28842  ...      2207      2652      4009
사망        443       219       570  ...        21        36       121
완치율   9.11202  0.436901  0.902836  ...  0.961656  0.918919  0.858458

[4 rows x 8 columns]

##DataFrame 편집
###재색인

In [1]:
import numpy as np
import pandas as pd
obj_s = pd.Series(np.arange(5.0), index=['d', 'b', 'a', 'c', 'e'])
print(obj_s)

obj_s = obj_s.reindex(['a', 'b', 'c', 'd', 'e'])
print(obj_s)

NameError: name 'np' is not defined

###drop메서드를 이용한 행 또는 열 삭제
####한개의 행 삭제

In [32]:
obj_new = obj_s.drop('c')
print(obj_new)

a    2.0
b    1.0
d    0.0
e    4.0
dtype: float64

#####두 개 이상의 행 삭제

In [37]:
obj_new = obj_s.drop(['b', 'd'])
print(obj_new)
new_co210419 = co210419.drop('인천')
print(new_co210419)

a    2.0
c    3.0
e    4.0
dtype: float64
       확진    격리해제   사망       완치율
지역
서울  35628  324643  443  9.112019
대구   9176    4009  219  0.436901
경기  31946   28842  570  0.902836
경북   3843    3515   77  0.914650
광주   2295    2207   21  0.961656
충남   2886    2652   36  0.918919
부산   4670    4009  121  0.858458

####DataFrame의 행 삭제 = 충남, 광주, 인천

In [39]:
new_co210419 = co210419.drop(['충남', '광주', '인천'])
print(new_co210419)

       확진    격리해제   사망       완치율
지역
서울  35628  324643  443  9.112019
대구   9176    4009  219  0.436901
경기  31946   28842  570  0.902836
경북   3843    3515   77  0.914650
부산   4670    4009  121  0.858458

####DataFrame 열 삭제 - '사망'

In [38]:
new_co210419 = new_co210419.drop('사망', axis=1)
print(new_co210419)

       확진    격리해제       완치율
지역
서울  35628  324643  9.112019
대구   9176    4009  0.436901
경기  31946   28842  0.902836
경북   3843    3515  0.914650
광주   2295    2207  0.961656
충남   2886    2652  0.918919
부산   4670    4009  0.858458

###데이터프레임 co210419의 '확진' 칼럼을 기준으로 내림차순 정렬

In [40]:
co210419_s = co210419.sort_values(by=["확진"], ascending=[False])

##DataFrame의 슬라이싱
###슬라이싱을 이용하여 확진자 수가 가장 많은 세 지역 정보로 새로운 데이터프레임 co210419_top3을 생성

In [12]:
co210419_top3 = co210419_s[:3]
print(co210419_top3)

       확진    격리해제   사망       완치율
지역
서울  35628  324643  443  9.112019
경기  31946   28842  570  0.902836
대구   9176    4009  219  0.436901

###head()함수를 이용하여 확진자 수가 가장 많은 세 지역 정보로 새로운 데이터프레임 co210419_top3을 생성

In [11]:
co210419_t3 = co210419_s.head(3)
print(co210419_t3)
co210419_b3 = co210419_s.tail(3)
print(co210419_b3)

       확진    격리해제   사망       완치율
지역
서울  35628  324643  443  9.112019
경기  31946   28842  570  0.902836
대구   9176    4009  219  0.436901
      확진  격리해제  사망       완치율
지역
경북  3843  3515  77  0.914650
충남  2886  2652  36  0.918919
광주  2295  2207  21  0.961656